services:
  mcp-server-test:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env.local
    volumes:
      # Model cache volume (local directory)
      - ./model_cache:/mnt/mcp_model
      # Logs volume for easier access
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    
  # Optional: Local MCP client for testing
  mcp-client-test:
    image: python:3.11-slim
    depends_on:
      - mcp-server-test
    volumes:
      - ./tests:/app/tests
      - ./client_scripts:/app/scripts
    working_dir: /app
    command: tail -f /dev/null  # Keep container running for manual testing
    environment:
      - MCP_SERVER_URL=http://mcp-server-test:8080
    restart: unless-stopped
